[package]
name = "render"
version = "0.1.0"
edition = "2024"

[dependencies]
colors = { path = "../colors" }
message = { path = "../message" }

bevy.workspace = true
ratatui.workspace = true
smol_str.workspace = true
